export default [
  {
    id: 0,
    title: 'PayMeBlue (Blue)',
    description: 'A payment solutions built with the needs of the local consumer demographic and economic climate in mind',
    tags: ['Mobile', 'Flutter'],
    categories: ['Mobile'],
    features: [
      'Push notifications',
      'Webview app with custom events and interactions',
      'Deep and deferred linking',
      'QR and Barcode generation and encryption',
      'Feature-flagging',
      'Live chat with firebase integration',
    ],
    logo: '/blue.png',
    liveUrl: 'https://paymeblue.com/app-redirect',
  },
  {
      id: 1,
      title: 'PayMeBlue (Blue) Business',
      description: 'A payment solutions built with the needs of the local consumer demographic and economic climate in mind',
      tags: ['Mobile', 'Flutter'],
      categories: ['Mobile'],
      features: [
        'Push notifications',
        'Sales analytics dashboard',
        'Mini app for staff management and sales tracking',
        'QR and Barcode generation and encryption',
        'Feature-flagging',
      ],
      logo: '/blue-business.png',
    },
    {
      id: 2,
      title: 'Goalspaces',
      description: 'A community-based, peer accountability social app that intends to encourage goal setting and goal achievement through bite-sized tasks',
      tags: ['Mobile', 'Flutter'],
      categories: ['Mobile'],
      features: [
        'Deep linking with custom events',
        'Deferred linking',
        'Gamification elements',
        'Live chat with websocket integration',
        'Image and video upload capabilities',
      ],
      liveUrl: 'https://mobile.goalspaces.com',
      logo: '/goalspaces.png',
    },
    {
      id: 3,
      title: 'LinkedIn - Redesign',
      description: 'A redesign of the LinkedIn web app home screen for better organisation and less information overload',
      tags: ['Design', 'Figma', 'Redesign'],
      categories: ['Design'],
      features: [
        'Simplified navigation',
        'Reduced visual clutter',
        'Improved content hierarchy',
        'Better mobile responsiveness',
        'Enhanced readability',
        'Modern design language',
      ],
      demoUrl: 'https://www.figma.com/proto/8gk6cVFu8dKecKMDiu8sZ3/Linkedin-Redesign?node-id=1-8&p=f&t=ym80JgrhCSAqjaob-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1&starting-point-node-id=1%3A8&show-proto-sidebar=1',
      logo: '/linkedin.png',
    },
    {
      id: 4,
      title: 'Battleship - Revised',
      description: 'A pure ESM javascript app to study JS functions, local and 3rd party modules, code structure and logical reasoning to create a game very much like and inspired by the popular game, "Battleship".',
      tags: ['NodeJS', 'Mini Games'],
      categories: ['Web'],
      features: [
        'Terminal-based gameplay with authentic CLI experience',
        'Random map generation',
        'Armored targets with unique hit mechanics',
        'Real-time in-game feedback and dynamic ASCII art',
        'Replay functionality with new mission generation',
      ],
      githubUrl: 'https://github.com/priscillaabhulimen/battleship-in-js',
      demoUrl: '#battleship',
    },
    {
      id: 5,
      title: 'Three-In-A-Row',
      description: 'A mini game used to study DOM, BOM and CSSOM manipulation, as well as API calls using fetch in vanilla javascript. The use of frameworks was intentionally avoided in order to strengthen knowledge in the cpre episodes of web development.',
      tags: ['Web', 'HTML5', 'CSS3', 'Mini Games'],
      categories: ['Web', 'Backend'],
      features: [
        'Pure vanilla JavaScript implementation',
        'DOM manipulation mastery',
        'Real-time game state management',
        'Responsive grid layout',
        'Win detection algorithm',
        'Score tracking system',
      ],
      githubUrl: 'https://github.com/priscillaabhulimen/three-in-a-row',
      demoUrl: 'https://three-in-a-row-demo.com',
    },
    {
      id: 6,
      title: 'Poker Draw',
      description: 'A mini game that explores logical reasoning and constraint-based app development to deliver an app that allows you to draw cards and then determines your best hand from that draw.',
      tags: ['Web', 'VueJS', 'SCSS', 'TailwindCSS', 'Mini Games'],
      categories: ['Web'],
      features: [
        'Card drawing mechanics',
        'Hand evaluation algorithm',
        'Poker hand ranking system',
        'Visual card animations',
        'Score calculation',
        'Multiple game modes',
      ],
      githubUrl: 'https://github.com/priscillaabhulimen/poker-app',
      liveUrl: 'https://vue-poker-app.netlify.app/basic',
    }
]